/**
 * main.c - NES emulator on an STM32F407VET6
 *
 * Hardware:
 *   ILI9341 320x240 TFT   SPI1  PA5/PA7 + PB6/PB7/PB8/PB9
 *   microSD (SDIO 4-bit)  PC8..PC12, PD2
 *   Gamepad input         USART1 PA9/PA10  (PC keyboard over USB-TTL)
 *
 * Boot flow:
 *   1. Initialise clocks, GPIO, SPI1 (display) and USART1 (input)
 *   2. Bring up the ILI9341
 *   3. Mount the SD card, find the first *.nes in the root, load it
 *   4. Run the emulator forever
 *
 * The ROM is read into a fixed buffer in CCM — see ROM buffer notes
 * in nes_port.c and the "Known limitations" section of the README.
 */

#include "main.h"
#include "ili9341.h"
#include "uart_pad.h"
#include "sd_card.h"
#include "nes_port.h"
#include "../InfoNES/InfoNES.h"
#include "../InfoNES/InfoNES_System.h"
#include "ff.h"

/*-------------------------------------------------------------------*/
/*  External HAL handles (generated by CubeMX from IOC)              */
/*-------------------------------------------------------------------*/
SPI_HandleTypeDef hspi1;
SD_HandleTypeDef  hsd;    /* SDIO — 板载卡槽 */
UART_HandleTypeDef huart1;

/*-------------------------------------------------------------------*/
/*  System Clock Configuration (168MHz from 8MHz HSE)                */
/*-------------------------------------------------------------------*/

void SystemClock_Config(void)
{
    RCC_OscInitTypeDef RCC_OscInitStruct = {0};
    RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

    /* Enable Power Control clock */
    __HAL_RCC_PWR_CLK_ENABLE();

    /* Configure HSE oscillator: 8MHz */
    RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
    RCC_OscInitStruct.HSEState = RCC_HSE_ON;
    RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
    RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
    RCC_OscInitStruct.PLL.PLLM = 8;
    RCC_OscInitStruct.PLL.PLLN = 336;
    RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV2;   /* PLLP = 84MHz */
    RCC_OscInitStruct.PLL.PLLQ = 7;                /* PLLQ = 48MHz (for USB/SDIO) */
    HAL_RCC_OscConfig(&RCC_OscInitStruct);

    /* Configure system clocks: HCLK=168MHz, PCLK1=42MHz, PCLK2=84MHz */
    RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK
                                | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
    RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
    RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
    RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV4;
    RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV2;
    HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_5);

    /* Enable ART Accelerator: prefetch buffer + instruction cache.
     * Without this, every Flash fetch costs 5 wait-states uncached.
     * The NES emulation hot loop (K6502_Step switch dispatch) is
     * entirely in Flash, so this gives 25-35% speedup. */
    __HAL_FLASH_PREFETCH_BUFFER_ENABLE();
    __HAL_FLASH_INSTRUCTION_CACHE_ENABLE();

    /* Enable FPU */
    SCB->CPACR |= ((3UL << 20) | (3UL << 22));
}

/*-------------------------------------------------------------------*/
/*  HAL MSP callbacks — GPIO + Clock config for each peripheral       */
/*-------------------------------------------------------------------*/

void HAL_SPI_MspInit(SPI_HandleTypeDef *hspi)
{
    if (hspi->Instance == SPI1) {
        __HAL_RCC_SPI1_CLK_ENABLE();
        __HAL_RCC_GPIOA_CLK_ENABLE();

        /* PA5=SCK, PA6=MISO, PA7=MOSI → AF5 */
        GPIO_InitTypeDef gpio = {0};
        gpio.Mode = GPIO_MODE_AF_PP;
        gpio.Pull = GPIO_NOPULL;
        gpio.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
        gpio.Alternate = GPIO_AF5_SPI1;

        gpio.Pin = GPIO_PIN_5 | GPIO_PIN_7;  /* SCK, MOSI */
        HAL_GPIO_Init(GPIOA, &gpio);

        gpio.Pin = GPIO_PIN_6;  /* MISO (optional) */
        gpio.Pull = GPIO_PULLUP;
        HAL_GPIO_Init(GPIOA, &gpio);

        /* SPI1 DMA TX: DMA2 Stream 3 Channel 3 */
        __HAL_RCC_DMA2_CLK_ENABLE();
    }
}

void HAL_UART_MspInit(UART_HandleTypeDef *huart)
{
    if (huart->Instance == USART1) {
        __HAL_RCC_USART1_CLK_ENABLE();
        __HAL_RCC_GPIOA_CLK_ENABLE();

        /* PA9=TX, PA10=RX → AF7 */
        GPIO_InitTypeDef gpio = {0};
        gpio.Mode = GPIO_MODE_AF_PP;
        gpio.Pull = GPIO_PULLUP;
        gpio.Speed = GPIO_SPEED_FREQ_HIGH;
        gpio.Alternate = GPIO_AF7_USART1;

        gpio.Pin = GPIO_PIN_9 | GPIO_PIN_10;
        HAL_GPIO_Init(GPIOA, &gpio);

        /* USART1 DMA: DMA2 Stream 7 Channel 4 (RX) */
        __HAL_RCC_DMA2_CLK_ENABLE();
    }
}

void HAL_SD_MspInit(SD_HandleTypeDef *hsd)
{
    __HAL_RCC_SDIO_CLK_ENABLE();
    __HAL_RCC_GPIOC_CLK_ENABLE();
    __HAL_RCC_GPIOD_CLK_ENABLE();

    /* PC8=D0, PC9=D1, PC10=D2, PC11=D3, PC12=CK → AF12 */
    GPIO_InitTypeDef gpio = {0};
    gpio.Mode = GPIO_MODE_AF_PP;
    gpio.Pull = GPIO_PULLUP;
    gpio.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
    gpio.Alternate = GPIO_AF12_SDIO;

    gpio.Pin = GPIO_PIN_8 | GPIO_PIN_9 | GPIO_PIN_10 | GPIO_PIN_11 | GPIO_PIN_12;
    HAL_GPIO_Init(GPIOC, &gpio);

    /* PD2=CMD → AF12 */
    gpio.Pin = GPIO_PIN_2;
    HAL_GPIO_Init(GPIOD, &gpio);

    /* SDIO DMA: DMA2 Stream 3 or Stream 6 */
    __HAL_RCC_DMA2_CLK_ENABLE();
}

/*-------------------------------------------------------------------*/
/*  SPI1 Init: ILI9341 Display                                       */
/*-------------------------------------------------------------------*/

static void MX_SPI1_Init(void)
{
    hspi1.Instance = SPI1;
    hspi1.Init.Mode = SPI_MODE_MASTER;
    hspi1.Init.Direction = SPI_DIRECTION_2LINES;
    hspi1.Init.DataSize = SPI_DATASIZE_8BIT;
    hspi1.Init.CLKPolarity = SPI_POLARITY_LOW;
    hspi1.Init.CLKPhase = SPI_PHASE_1EDGE;
    hspi1.Init.NSS = SPI_NSS_SOFT;
    hspi1.Init.BaudRatePrescaler = SPI_BAUDRATEPRESCALER_2; /* 84/2=42MHz */
    hspi1.Init.FirstBit = SPI_FIRSTBIT_MSB;
    hspi1.Init.TIMode = SPI_TIMODE_DISABLE;
    hspi1.Init.CRCCalculation = SPI_CRCCALCULATION_DISABLE;
    HAL_SPI_Init(&hspi1);

    ILI9341_DMA_Init();
}

/*-------------------------------------------------------------------*/
/*  SDIO Init: 板载 microSD 卡槽 (PC8-PC12, PD2)                     */
/*-------------------------------------------------------------------*/

static void MX_SDIO_Init(void)
{
    hsd.Instance = SDIO;
    hsd.Init.ClockEdge = SDIO_CLOCK_EDGE_RISING;
    hsd.Init.ClockBypass = SDIO_CLOCK_BYPASS_DISABLE;
    hsd.Init.ClockPowerSave = SDIO_CLOCK_POWER_SAVE_DISABLE;
    hsd.Init.BusWide = SDIO_BUS_WIDE_1B;  /* 初始化用1-bit, 后续切4-bit */
    hsd.Init.HardwareFlowControl = SDIO_HARDWARE_FLOW_CONTROL_DISABLE;
    hsd.Init.ClockDiv = 0;  /* SDIOCLK = 48MHz / (0+2) = 24MHz */
    HAL_SD_Init(&hsd);
}

/*-------------------------------------------------------------------*/
/*  USART1 Init: gamepad input from PC                               */
/*-------------------------------------------------------------------*/

static void MX_USART1_UART_Init(void)
{
    huart1.Instance = USART1;
    huart1.Init.BaudRate = 115200;
    huart1.Init.WordLength = UART_WORDLENGTH_8B;
    huart1.Init.StopBits = UART_STOPBITS_1;
    huart1.Init.Parity = UART_PARITY_NONE;
    huart1.Init.Mode = UART_MODE_TX_RX;
    huart1.Init.HwFlowCtl = UART_HWCONTROL_NONE;
    huart1.Init.OverSampling = UART_OVERSAMPLING_16;
    HAL_UART_Init(&huart1);

    /* RX interrupt handled by UART_Pad_Init → HAL_UART_RxCpltCallback */
}

/*-------------------------------------------------------------------*/
/*  GPIO Init                                                        */
/*-------------------------------------------------------------------*/

static void MX_GPIO_Init(void)
{
    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();
    __HAL_RCC_GPIOC_CLK_ENABLE();
    __HAL_RCC_GPIOD_CLK_ENABLE();

    GPIO_InitTypeDef gpio = {0};

    /* PB6: LCD_CS, PB7: LCD_RST, PB8: LCD_DC, PB9: LCD_BL */
    gpio.Mode = GPIO_MODE_OUTPUT_PP;
    gpio.Pull = GPIO_NOPULL;
    gpio.Speed = GPIO_SPEED_FREQ_HIGH;

    gpio.Pin = GPIO_PIN_6 | GPIO_PIN_7 | GPIO_PIN_8 | GPIO_PIN_9;
    HAL_GPIO_Init(GPIOB, &gpio);

    /* PC13: DEBUG_LED */
    gpio.Mode = GPIO_MODE_OUTPUT_PP;
    gpio.Pull = GPIO_NOPULL;
    gpio.Speed = GPIO_SPEED_FREQ_HIGH;
    gpio.Pin = GPIO_PIN_13;
    HAL_GPIO_Init(GPIOC, &gpio);

    /* PA0: USER_BTN (input) */
    gpio.Mode = GPIO_MODE_INPUT;
    gpio.Pull = GPIO_PULLUP;
    gpio.Pin = GPIO_PIN_0;
    HAL_GPIO_Init(GPIOA, &gpio);

    /* Set initial states */
    HAL_GPIO_WritePin(GPIOB, GPIO_PIN_6 | GPIO_PIN_7 | GPIO_PIN_8, GPIO_PIN_SET);
    HAL_GPIO_WritePin(GPIOB, GPIO_PIN_9, GPIO_PIN_SET);
    HAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, GPIO_PIN_SET); /* LED off */

    /* SDIO pins (PC8-PC12, PD2): configured by HAL_SD_Init() automatically,
     * no manual GPIO init needed here. */
}

/*-------------------------------------------------------------------*/
/*  SysTick Handler (1ms)                                            */
/*-------------------------------------------------------------------*/

void SysTick_Handler(void)
{
    HAL_IncTick();
    NES_TickInc();
}

/*-------------------------------------------------------------------*/
/*  main() — NES Emulator entry point                                */
/*-------------------------------------------------------------------*/

int main(void)
{
    /* HAL Init */
    HAL_Init();
    SystemClock_Config();

    /* Peripheral init */
    MX_GPIO_Init();
    MX_SPI1_Init();
    MX_SDIO_Init();
    MX_USART1_UART_Init();

    /* Display */
    printf("ILI9341 init...\n");
    NES_DisplayInit();

    /* Gamepad input */
    UART_Pad_Init();
    printf("Input ready (WASD / J / K / Enter / Space)\n");

    /* SD card — optional. The ROM is embedded in flash, so no card is
     * needed to run. The driver is here as a base for loading ROMs at
     * runtime; see "Known limitations" in the README. */
    printf("SD card init...\n");
    if (SD_Init() == 0) {
        printf("SD card ready\n");
    } else {
        printf("No SD card (not required)\n");
    }

    /* Emulator core + ROM */
    printf("InfoNES init...\n");
    InfoNES_Init();

    if (InfoNES_Menu() < 0) {
        printf("No ROM loaded\n");
        ILI9341_FillRect(0, 100, 320, 40, ILI9341_RED);  /* red bar = ROM error */
        while (1) {
            HAL_GPIO_TogglePin(GPIOC, GPIO_PIN_13);
            HAL_Delay(200);
        }
    }

    printf("Starting emulation\n");
    ILI9341_FillScreen(ILI9341_BLACK);
    HAL_GPIO_WritePin(GPIOC, GPIO_PIN_13, GPIO_PIN_RESET);  /* LED on = running */

    /* Never returns */
    InfoNES_Main();

    /* Not reached */
    while (1);
}

/*-------------------------------------------------------------------*/
/*  Error Handler                                                    */
/*-------------------------------------------------------------------*/

void Error_Handler(void)
{
    __disable_irq();
    while (1) {
        HAL_GPIO_TogglePin(GPIOC, GPIO_PIN_13);
        for (volatile int i = 0; i < 500000; i++);
    }
}

/*-------------------------------------------------------------------*/
/*  assert_failed (for HAL)                                          */
/*-------------------------------------------------------------------*/

#ifdef USE_FULL_ASSERT
void assert_failed(uint8_t *file, uint32_t line)
{
    printf("ASSERT: %s:%lu\n", (char *)file, line);
    Error_Handler();
}
#endif
