/**
 * sd_card.c - microSD card driver via SDIO 4-bit for STM32F407VET6
 *
 * Pin mapping (on-board slot):
 *   PC8  = SDIO_D0
 *   PC9  = SDIO_D1
 *   PC10 = SDIO_D2
 *   PC11 = SDIO_D3
 *   PC12 = SDIO_CK
 *   PD2  = SDIO_CMD
 *
 * Uses HAL SDIO functions + FatFs diskio layer.
 * Much faster than SPI (~24MB/s vs ~2MB/s for SPI at 21MHz).
 */

#include <string.h>
#include "main.h"
#include "sd_card.h"
#include "ff.h"

/* FatFs requires get_fattime() */
DWORD get_fattime(void) { return 0; }

/*-------------------------------------------------------------------*/
/*  External SDIO handle (generated by CubeMX)                        */
/*-------------------------------------------------------------------*/
extern SD_HandleTypeDef hsd;

static int sd_initialized = 0;

/*-------------------------------------------------------------------*/
/*  SD_Init / disk_initialize                                         */
/*-------------------------------------------------------------------*/

int SD_Init(void)
{
    if (sd_initialized) return 0;

    /* HAL_SD_Init does: clock enable, GPIO AF config, card detection,
     * voltage validation, card identification, RCA assignment,
     * and switches to 4-bit wide bus mode. */
    if (HAL_SD_Init(&hsd) != HAL_OK) {
        return -1;
    }

    /* Configure wide bus (4-bit) if supported */
    if (HAL_SD_ConfigWideBusOperation(&hsd, SDIO_BUS_WIDE_4B) != HAL_OK) {
        /* Fall back to 1-bit */
        HAL_SD_ConfigWideBusOperation(&hsd, SDIO_BUS_WIDE_1B);
    }

    sd_initialized = 1;
    return 0;
}

DSTATUS disk_initialize(BYTE pdrv)
{
    (void)pdrv;
    return (SD_Init() == 0) ? RES_OK : STA_NOINIT;
}

/*-------------------------------------------------------------------*/
/*  disk_status                                                      */
/*-------------------------------------------------------------------*/

DSTATUS disk_status(BYTE pdrv)
{
    (void)pdrv;
    if (!sd_initialized) return STA_NOINIT;

    /* Check if card is still present and responsive */
    HAL_SD_CardStateTypeDef state = HAL_SD_GetCardState(&hsd);
    if (state == HAL_SD_CARD_TRANSFER ||
        state == HAL_SD_CARD_STANDBY) {
        return RES_OK;
    }
    return STA_NOINIT;
}

/*-------------------------------------------------------------------*/
/*  disk_read : Read sector(s) via SDIO                              */
/*-------------------------------------------------------------------*/

DRESULT disk_read(BYTE pdrv, BYTE *buff, LBA_t sector, UINT count)
{
    (void)pdrv;
    if (!sd_initialized) return RES_NOTRDY;
    if (count == 0) return RES_PARERR;

    /* HAL_SD_ReadBlocks uses block addressing for SDHC/SDXC cards,
     * and byte addressing for older SDSC cards. We pass the LBA
     * sector number directly — HAL handles the conversion. */
    HAL_StatusTypeDef status = HAL_SD_ReadBlocks(&hsd, buff, sector, count, 5000);
    if (status != HAL_OK) {
        return RES_ERROR;
    }

    /* Wait for transfer to complete (SDIO uses DMA or interrupt) */
    /* For blocking mode, HAL_SD_ReadBlocks already waits */
    /* But check that the card is back in transfer state */
    HAL_SD_CardStateTypeDef state;
    uint32_t timeout = 100000;
    do {
        state = HAL_SD_GetCardState(&hsd);
        timeout--;
    } while (state != HAL_SD_CARD_TRANSFER && timeout > 0);

    if (timeout == 0) return RES_ERROR;
    return RES_OK;
}

/*-------------------------------------------------------------------*/
/*  disk_write : Write sector(s) via SDIO                            */
/*-------------------------------------------------------------------*/

DRESULT disk_write(BYTE pdrv, const BYTE *buff, LBA_t sector, UINT count)
{
    (void)pdrv;
    if (!sd_initialized) return RES_NOTRDY;
    if (count == 0) return RES_PARERR;

    HAL_StatusTypeDef status = HAL_SD_WriteBlocks(&hsd, (uint8_t *)buff, sector, count, 5000);
    if (status != HAL_OK) {
        return RES_ERROR;
    }

    /* Wait for transfer complete */
    HAL_SD_CardStateTypeDef state;
    uint32_t timeout = 100000;
    do {
        state = HAL_SD_GetCardState(&hsd);
        timeout--;
    } while (state != HAL_SD_CARD_TRANSFER && timeout > 0);

    if (timeout == 0) return RES_ERROR;
    return RES_OK;
}

/*-------------------------------------------------------------------*/
/*  disk_ioctl : Control functions                                   */
/*-------------------------------------------------------------------*/

DRESULT disk_ioctl(BYTE pdrv, BYTE cmd, void *buff)
{
    (void)pdrv;
    if (!sd_initialized) return RES_NOTRDY;

    switch (cmd) {
        case CTRL_SYNC:
            /* SDIO is self-synchronizing, nothing extra needed */
            return RES_OK;

        case GET_SECTOR_COUNT: {
            HAL_SD_CardInfoTypeDef cardInfo;
            HAL_SD_GetCardInfo(&hsd, &cardInfo);
            *(DWORD *)buff = (DWORD)(cardInfo.LogBlockNbr);
            return RES_OK;
        }

        case GET_SECTOR_SIZE:
        case GET_BLOCK_SIZE:
            *(DWORD *)buff = 512;
            return RES_OK;

        default:
            return RES_PARERR;
    }
}

/*-------------------------------------------------------------------*/
/*  Convenience functions                                            */
/*-------------------------------------------------------------------*/

int SD_FileExists(const char *path)
{
    FILINFO fno;
    return (f_stat(path, &fno) == FR_OK) ? 1 : 0;
}

long SD_FileSize(const char *path)
{
    FILINFO fno;
    return (f_stat(path, &fno) == FR_OK) ? (long)fno.fsize : -1;
}

void SD_PowerOn(void)
{
    /* SDIO card is always powered when inserted */
}

void SD_PowerOff(void)
{
    HAL_SD_DeInit(&hsd);
    sd_initialized = 0;
}

void SD_DeInit(void)
{
    SD_PowerOff();
}
