#!/usr/bin/env python3
"""
nes2c.py - Embed a .nes ROM into the firmware as a C array.

The emulator keeps the ROM in flash rather than RAM: the STM32F407 has
512 KB of flash but only 192 KB of RAM, and the emulator core plus the
frame buffer already consume all of the RAM. Writing the ROM as a
const array lets the linker place it in flash, where it is directly
readable, so it costs no RAM at all.

Usage:
    python3 tools/nes2c.py <rom.nes> [output.c]

Defaults to writing Core/Src/rom_data.c.

The ROM itself is your responsibility — do not redistribute ROMs you do
not have the rights to.
"""

import os
import sys

DEFAULT_OUTPUT = os.path.join("Core", "Src", "rom_data.c")
BYTES_PER_LINE = 16


def main():
    if len(sys.argv) < 2:
        print(__doc__.strip())
        return 1

    rom_path = sys.argv[1]
    out_path = sys.argv[2] if len(sys.argv) > 2 else DEFAULT_OUTPUT

    if not os.path.isfile(rom_path):
        print(f"error: no such file: {rom_path}")
        return 1

    with open(rom_path, "rb") as f:
        data = f.read()

    if len(data) < 16:
        print(f"error: {rom_path} is too small to be a NES ROM")
        return 1

    if data[:4] != b"NES\x1a":
        print(f"error: {rom_path} is not a valid .nes file (bad magic)")
        print(f"       expected b'NES\\x1a', got {data[:4]!r}")
        return 1

    prg_16k = data[4]
    chr_8k = data[5]
    mapper = (data[7] & 0xF0) | (data[6] >> 4)

    out_dir = os.path.dirname(out_path)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)

    with open(out_path, "w") as f:
        f.write("/*\n")
        f.write(f" * Generated by tools/nes2c.py from {os.path.basename(rom_path)}\n")
        f.write(" *\n")
        f.write(" * Do not edit by hand, and do not commit this file unless you\n")
        f.write(" * hold the rights to the ROM it contains.\n")
        f.write(f" *\n")
        f.write(f" * PRG: {prg_16k * 16} KB   CHR: {chr_8k * 8} KB   Mapper: {mapper}\n")
        f.write(" */\n\n")
        f.write('#include "rom_data.h"\n\n')

        f.write(f"const unsigned char nes_rom_data[{len(data)}] = {{\n")
        for i in range(0, len(data), BYTES_PER_LINE):
            chunk = data[i:i + BYTES_PER_LINE]
            f.write("    " + " ".join(f"0x{b:02x}," for b in chunk) + "\n")
        f.write("};\n\n")

        f.write(f"const unsigned int nes_rom_size = {len(data)};\n")

    print(f"Wrote {out_path}")
    print(f"  {len(data)} bytes  ({len(data) / 1024:.1f} KB)")
    print(f"  PRG {prg_16k * 16} KB, CHR {chr_8k * 8} KB, mapper {mapper}")
    print()
    print("Rebuild and flash the firmware to run it.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
